---
# defaults file for jaspar
jaspar_app: jaspar_deployment

jaspar_base_dir: /var/www/apps
jaspar_data_dir: /tmp/jaspar-data

jaspar_hostname: '{{ ansible_host }}'
jaspar_user: '{{ ansible_user }}'

admin_email: somebody@uio.no
send_to_email: somebody@uio.no
smtp_host: localhost
smtp_user: nobody
smtp_password: ''

jaspar_port: 80
jaspar_secure: false

redeploy_static_content: true
unprivileged: true
final_privileged: true