---
# tasks file for 10-root-selinux

#TODO: Ansiblelized script ?
- name: Initialise directories.
  become: true
  ansible.builtin.command:
    cmd: '{{ jaspar_app_dir }}/deploy/10-root-selinux.sh'
    chdir: '{{ jaspar_app_dir }}'

- name:  Allow Apache to execute tmp files?
  tags:
  - selinux
  become: true
  ansible.posix.seboolean:
    name: httpd_tmp_exec
    state: true
    persistent: true

- name:  Allow Apache to map executable memory.
  tags:
  - selinux
  become: true
  ansible.posix.seboolean:
    name: httpd_execmem
    state: true
    persistent: true
