---
# tasks file for 10-root-selinux-sqlite

##TODO: Ansiblelized script ?
#- name: Set permissions on the application directory for SQLite write access.
#  become: true
#  ansible.builtin.command:
#    cmd: '{{ jaspar_app_dir }}/deploy/10-root-selinux-sqlite.sh'
#    chdir: '{{ jaspar_app_dir }}'
#



#- name: List temp directory
#  tags:
#    - selinux
#  ansible.builtin.find:
#    path: '{{ jaspar_app_dir }}/temp'
#    file_type: directory
#  register: jaspar_temp

- name: Set permissions for temp directory write access
  tags:
    - selinux
  become: true
  community.general.sefcontext:
    target: '{{ jaspar_app_dir }}/temp(/.*)?'
    setype: httpd_sys_rw_content_t
    ftype: a
    state: present
#  loop: '{{ jaspar_temp.files  | map(attribute="path") }}'


- name: Restore default SELinux security contexts for temp
  tags:
    - selinux
  become: true
  ansible.builtin.command:
    cmd: 'restorecon -R {{ jaspar_app_dir }}/temp'
#  loop: '{{ jaspar_temp.files  | map(attribute="path") }}'


- name: set an ACL for Apache.
  tags:
    - jaspar
    - ACL-permission
  ansible.posix.acl:
    path: '{{ jaspar_app_dir }}/temp'
    entity: '{{ apache_user }}'
    etype: user
    permissions: rwx
    recursive: true
    state: present


- name: Restore default SELinux security contexts for static dir
  tags:
    - selinux
  become: true
  ansible.builtin.command:
    cmd: 'restorecon -R {{ jaspar_app_dir }}/static'

